#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt no_share_history

alias e='emacsclient -t'
alias ccat="pygmentize -O linenos=1,style=emacs"

# Python-stuff
alias mkvirtualenv3='mkvirtualenv --python=$(which python3)'
source "/usr/local/bin/virtualenvwrapper.sh"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mkaloer/Applications/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/mkaloer/Applications/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mkaloer/Applications/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/mkaloer/Applications/google-cloud-sdk/completion.zsh.inc'; fi


export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export GOPATH="$HOME/go"
export GOBIN="$HOME/go/bin"
export PATH=$PATH:$HOME/go/bin
